Set attrs v22.1.0 as min version (#304)
because the min_len validator has been introduced there.
fixes E   AttributeError: module 'attrs.validators' has no attribute 'min_len'